### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-heroku-maven-plugin#4]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
we'll find someone to do this task, soon

**Comment by dmarkov** [comment]
@nathansgreen it's in your hands now, please proceed

**Comment by dmarkov** [comment]
@maurezen thanks for reporting! I topped your account for 15 mins, transaction 49997556

**Comment by nathansgreen** [comment]
@dmarkov @maurezen I created PR #5 but haven't seen activity to get it reviewed. Anything I should do?

**Comment by yegor256** [comment]
@nathansgreen we'll find a reviewer soon, thanks for the PR!

**Comment by nathansgreen** [comment]
@maurezen PR #5 has been merged. Please close the issue.

**Comment by dmarkov** [comment]
@nathansgreen thanks, paid, **30 mins** to your account, payment ID is `AP-5VJ27404GD162805S`

+30 added to your rating, current score is: [+130](http://www.netbout.com/b/35107?open=rating)
